### ISSUE TITLE
您好，关于系统的一些问题想请教

### ISSUE THREAD

**Issue by greysonOuyang** [itning/hrms#1]
您好，请问您的这个系统的数据库SQL有吗?如果能提供的话，十分感谢。

**Comment by itning** [comment]
> 您好，请问您的这个系统的数据库SQL有吗?如果能提供的话，十分感谢。

JPA自动建库建表

**Comment by greysonOuyang** [comment]
好的 感谢

**Comment by greysonOuyang** [comment]
您好，该项目运行的时候报错 Table 'hrms.wage' doesn't exist。我查看了下数据库，确实缺少这个表，实体类的注解也没有错，这是什么原因造成的呢？

**Comment by greysonOuyang** [comment]
问题解决了，感谢您的开源
