### ISSUE TITLE
您好，请问默认的登录用户名和密码是多少呢？

### ISSUE THREAD

**Issue by greysonOuyang** [itning/hrms#2]

**Comment by itning** [comment]
默认在这里配置

[application-dev.yml](https://github.com/itning/hrms/blob/dev/src/main/resources/application-dev.yml#L13)

[该文件](https://github.com/itning/hrms/blob/dev/src/main/resources/application.yml#L3)指向dev文件

**Comment by greysonOuyang** [comment]
您指向的是数据库的用户名和密码吗？这一块我修改了，很抱歉再次打扰您，我没有学习过springsecurity，想先登陆上去看下效果再去修改。系统登录的默认用户名和密码我不知道

**Comment by itning** [comment]
> 您指向的是数据库的用户名和密码吗？这一块我修改了，很抱歉再次打扰您，我没有学习过springsecurity，想先登陆上去看下效果再去修改。系统登录的默认用户名和密码我不知道

在``user``表中添加即可，权限(角色)是``ADMIN``

**Comment by greysonOuyang** [comment]
感谢！终于登录上去了，请问系统是正在开发吗？还是说我的bug，只有添加信息的功能
