### ISSUE TITLE
sql

### ISSUE THREAD

**Issue by lingxicom** [itning/hrms#5]
数据文件，给一个sql

**Comment by itning** [comment]
See #3

**Comment by lingxicom** [comment]
收到了，非常感谢，祝一切顺利！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "itning/hrms"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月6日(星期一) 下午3:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [itning/hrms] sql (#5)





 
Closed #5.
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
